sudo: required
language: node_js
node_js:
- '10'
services:
- docker
- redis-server
branches:
  only:
  - master
before_install: ./scripts/beforeInstall.sh
install:
- npm i
- export CHANGED=$(lerna changed)
- lerna bootstrap
script:
- npm run lint
- npm run test
- ./scripts/createVersion.sh
# deploy:
#   skip_cleanup: true
#   provider: script
#   script: PRIVATE_REGISTRY=docker.io/hkube npm run build
#   on:
#     branch: master
